#!/bin/bash  echo "ALX School"

[A[A[A[B[[B[B[B[B[B[A[B[D[D[D[D[D[D[C[C[C[C[C[C[C



[A[A[A[A[A[A[A[A[B[C[C[C[C[C[C[C[C[[[A[C[C[C[C[C[C[C[C[C[[6~[A[Ccd
[D[A[A[B[B[B[A[D[A[C[C[A[B[B[Aclear









